// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKe0PVnK-ygU0s0G46RUx30usAaqyvNS0',
    appId: '1:597083282763:web:22af3f00e56ddc09bf9cce',
    messagingSenderId: '597083282763',
    projectId: 'whatsapp-619',
    authDomain: 'whatsapp-619.firebaseapp.com',
    storageBucket: 'whatsapp-619.appspot.com',
    measurementId: 'G-2HD0CQGY84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaApBoluvb3BfSxZML1K8oyYxd9Mar9pY',
    appId: '1:597083282763:android:87fdd4c6ae54cc5bbf9cce',
    messagingSenderId: '597083282763',
    projectId: 'whatsapp-619',
    storageBucket: 'whatsapp-619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz2HfWwlgVOnuFikQhmzlc8eFVPjG3RuY',
    appId: '1:597083282763:ios:f62e2b46d3e826e3bf9cce',
    messagingSenderId: '597083282763',
    projectId: 'whatsapp-619',
    storageBucket: 'whatsapp-619.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz2HfWwlgVOnuFikQhmzlc8eFVPjG3RuY',
    appId: '1:597083282763:ios:7bb300e5db0485debf9cce',
    messagingSenderId: '597083282763',
    projectId: 'whatsapp-619',
    storageBucket: 'whatsapp-619.appspot.com',
    iosBundleId: 'com.example.whatsapp.RunnerTests',
  );
}
